<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinderStore.Backend.Application\FinderStore.Backend.Application.csproj" />
    <ProjectReference Include="..\FinderStore.Backend.Domain\FinderStore.Backend.Domain.csproj" />
    <ProjectReference Include="..\FinderStore.Backend.Infrastructure\FinderStore.Backend.Infrastructure.csproj" />
  </ItemGroup>

</Project>
